List pizzaItems = [
  {
    'image': 'asset/margherita.png',
    'itemName': 'Margherita',
    'rating': '4/5',
    'weight': '200 g',
    'detailShow': false,
    'isBookMark': false,
    'detail': "Queijo coberto com tomates fatiados com um toque de manjericão.",
    'prize': 60,
  },
  {
    'image': 'asset/pepperoni.png',
    'rating': '5/5',
    'detailShow': false,
    'isBookMark': false,
    'itemName': 'Pepperoni',
    'detail':
        "Fatias de pepperoni servidas sobre generosa camada de queijo e molho de tomate.",
    'weight': '300 g',
    'prize': 60,
  },
  {
    'image': 'asset/Farmhouse-removebg-preview.png',
    'rating': '4/5',
    'detailShow': false,
    'isBookMark': false,
    'itemName': 'Vegetariana',
    'detail':
        "Molho de tomate, queijo, tomate, champignon, pimentão verde, cebola e azeitonas verdes.",
    'weight': '250 g',
    'prize': 60,
  },
  {
    'image': 'asset/4queijos.png',
    'rating': '4/5',
    'detailShow': false,
    'itemName': '4 Queijos',
    'detail': "Molho de tomate, queijo, provolone, parmesão e cream cheese.",
    'weight': '300 g',
    'prize': 60,
  },
  {
    'image': 'asset/napolitana.png',
    'rating': '5/5',
    'detailShow': false,
    'isBookMark': false,
    'itemName': 'Napolitana',
    'detail': "Parmesão, queijo, rodelas de tomates, orégano e alho.",
    'weight': '320 g',
    'prize': 60,
  },
];
List hambugerItem = [
  {
    'image': 'asset/quarter_pounder.png',
    'itemName': 'Quarteirao',
    'rating': '3/5',
    'isBookMark': false,
    'weight': '250 g',
    'detailShow': false,
    'detail':
        "Um hambúrguer, queijo cheddar, picles, cebola, ketchup, mostarda e pão com gergelim.",
    'prize': 25,
  },
  {
    'image': 'asset/dcb.png',
    'itemName': 'Cheeseburger',
    'rating': '5/5',
    'weight': '250 g',
    'isBookMark': false,
    'detailShow': false,
    'detail':
        "Dois hambúrgueres, queijo cheddar derretido, picles, cebola picada, ketchup e mostarda.",
    'prize': 25,
  },
  {
    'image': 'asset/bacon_chicken_nugget.png',
    'itemName': 'Bacon Chicken',
    'rating': '5/5',
    'weight': '250 g',
    'isBookMark': false,
    'detailShow': false,
    'detail':
        "Frango empanado, maionese, bacon, alface americana e pão com gergelim.",
    'prize': 25,
  },
];
List bebidasItem = [
  {
    'image': 'asset/refri.png',
    'isBookMark': false,
    'itemName': 'Refrigerente',
    'rating': '4/5',
    'weight': '400 ml',
    'detailShow': false,
    'detail': "Refrigerante de cola, 400ml.",
    'prize': 8,
  },
  {
    'image': 'asset/suco_laranja.png',
    'isBookMark': false,
    'itemName': 'Suco de laranja',
    'rating': '4/5',
    'weight': '400 ml',
    'detailShow': false,
    'detail': "Suco de laranja, 400ml",
    'prize': 7,
  },
  {
    'image': 'asset/cerveja.png',
    'isBookMark': false,
    'itemName': 'Cerveja Longneck',
    'rating': '4/5',
    'weight': '350 ml',
    'detailShow': false,
    'detail': "Cerveja longneck, 350ml",
    'prize': 10,
  },
];
